image: node:latest

stages:
  - build
  - linting
  - test
  - deploy

build:
  stage: build
  cache:
    paths:
      - node_modules/
      - /root/.cache/Cypress
  script:
    - npm install --quiet
    - npm run build --prod
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-ci/

linting:
  stage: linting
  cache:
    paths:
      - node_modules/
      - /root/.cache/Cypress
  script:
    - npx ng lint
  dependencies:
    - build
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-ci/

test:unit:
  stage: test
  cache:
    paths:
      - node_modules/
      - /root/.cache/Cypress
  script:
    - npm run test
  dependencies:
    - build
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-ci/

test:e2e:
  stage: test
  cache:
    paths:
      - node_modules/
      - /root/.cache/Cypress
  dependencies:
    - build
    - linting
  script:
    - npm run e2e
  artifacts:
    paths:
      - cypress/screenshots
      - cypress/videos
    expire_in: 1 day
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-ci/

deploy_prod:
  stage: deploy
  environment:
    name: production
    url: $FIREBASE_URL
  only:
   - master
  dependencies:
    - build
  cache:
    policy: pull
    paths:
      - node_modules/
  script:
    - npm run deploy
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-ci/

